### ISSUE TITLE
/confirmAccount page

### ISSUE THREAD

**Issue by RickNabb** [YesAndGames/ag-website-client#35]
We need a page that users can be directed to in order to confirm their account. It would be nice if it could have the look and feel of the site, and have some client-side element generation based on query string params "username" and "confirmUUID".

Ultimately, onload the page will shoot off an AJAX request to the API to confirm the account of the username with that UUID, and get a response back that would generate a "You confirmed your account!" or "Your account has already be confirmed!" response type thing.

It would probably be best for a link to the main site to be underneath the message.

**Comment by weslo** [comment]
done
